from enum import Enum
class ResponseEnum(Enum):
    file_type_not_allowed = "File type is not allowed."
    file_size_exceeded = "File size exceeds the maximum limit."
    file_uploaded_success = "File uploaded success."
    file_uploaded_failed = "File upload failed."
    file_valid = "File is valid."
    file_processing_failed = "File processing failed."
    file_processed_success = "File processed successfully."
    no_files_to_process = "No files to process."
    file_not_found = "File not found."
    project_not_found = "Project not found."
    nlp_indexing_started = "NLP indexing started."
    INSERT_INTO_VECTOR_DB_FAILED = "Inserting data into database failed."
    indexing_failed = "Indexing failed."
    INSERT_INTO_VECTOR_DB_SUCCESS = "Data inserted into database successfully."
    indexing_success = "Indexing completed successfully."
    VECTOR_DB_COLLECTION_INFO_RETRIEVED = "Vector DB collection info retrieved successfully."
    VECTOR_DB_COLLECTION_NOT_FOUND = "Vector DB collection not found."
    VECTOR_DB_SEARCH_FAILED = "Vector DB search failed."
    VECTOR_DB_SEARCH_SUCCESS = "Vector DB search completed successfully."
    ANSWER_GENERATION_FAILED = "Answer generation failed."
    ANSWER_GENERATION_SUCCESS = "Answer generated successfully."
    RAG_PROCESSING_FAILED = "RAG processing failed."
    RAG_PROCESSING_SUCCESS = "RAG processing completed successfully."

